# Generated by Django 3.1.8 on 2021-04-17 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Watches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Eprms', max_length=50, verbose_name='Name')),
                ('image', models.ImageField(blank=True, null=True, upload_to='watches/', verbose_name='Image')),
                ('model', models.CharField(blank=True, max_length=15, null=True, verbose_name='Model Number')),
            ],
        ),
        migrations.CreateModel(
            name='Varient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Eprms', max_length=50, verbose_name='Name')),
                ('image', models.ImageField(blank=True, null=True, upload_to='watches/', verbose_name='Image')),
                ('model', models.CharField(blank=True, max_length=15, null=True, verbose_name='Varient Number')),
                ('watch', models.ForeignKey(default='TX', on_delete=django.db.models.deletion.CASCADE, to='wishlists.watches', verbose_name='Varient')),
            ],
        ),
    ]
