# Generated by Django 3.1.8 on 2021-04-20 21:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wishlists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='varient',
            name='waiting_list',
            field=models.ManyToManyField(blank=True, related_name='varient_list', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='varient',
            name='name',
            field=models.CharField(default='varient', max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='varient',
            name='watch',
            field=models.ForeignKey(default='TX', on_delete=django.db.models.deletion.CASCADE, related_name='varient', to='wishlists.watches', verbose_name='Varient'),
        ),
        migrations.AlterField(
            model_name='watches',
            name='name',
            field=models.CharField(default='watch', max_length=50, verbose_name='Name'),
        ),
    ]
