# Generated by Django 3.1.8 on 2021-04-20 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlists', '0002_auto_20210420_2129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='varient',
            name='waiting_list',
        ),
    ]
