# Generated by Django 3.1.8 on 2021-04-16 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='national_id',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True, verbose_name='Licence ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('employee', 'Employee'), ('admin', 'Administration'), ('subadmin', 'SubAdmin'), ('cust', 'Customer')], max_length=100, null=True),
        ),
    ]
